# Generated by Django 4.0.1 on 2022-02-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0002_alter_company_options_alter_vehicle_options_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1)),
                ('service_status', models.CharField(choices=[('F', 'Finished'), ('X', 'Unfinished')], default='X', max_length=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.user')),
            ],
        ),
    ]
