# Generated by Django 4.0.1 on 2022-02-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0004_userservicevehicle_remove_userservice_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='service',
            new_name='service_cost',
        ),
    ]
