# Generated by Django 4.0.1 on 2022-02-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0005_rename_service_vehicle_service_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservicevehicle',
            name='service_status',
            field=models.CharField(choices=[('X', 'Unfinished'), ('F', 'Finished')], default='X', max_length=1),
        ),
    ]
